# Disable config changes being applied immeadiatley
live_config_reload = false

[env]
term = "xterm-256color"

# Font configuration
[font]
size = 15

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Regular Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

# Monokia Colors
[colors.primary]
background = "#262626"
foreground = "#F8F8F2"

[colors.normal]
black = "#272822"
red = "#F92672"
green = "#A6E22E"
yellow = "#F4BF75"
blue = "#66D9EF"
magenta = "#AE81FF"
cyan = "#A1EFE4"
white = "#F8F8F2"

[colors.bright]
black = "#75715E"
red = "#F92672"
green = "#A6E22E"
yellow = "#F4BF75"
blue = "#66D9EF"
magenta = "#AE81FF"
cyan = "#A1EFE4"
white = "#F9F8F5"


[window.padding]
x = 10
y = 10
