wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/tokyo-night-theme/cosmic_tokyo_night.png
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/tokyo-night-theme/cosmic_tokyo_night.png
}
