wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/tokyo-night-theme/cosmicrobotretro_upscayl_2x_digital-art-4x.png
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/tokyo-night-theme/cosmicrobotretro_upscayl_2x_digital-art-4x.png
}
