general {
    gaps_in = 2.5
    gaps_out = 5
    float_gaps = 5

    border_size = 1

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    # will come and change this later
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # find a way to only have this enabled on floating windows
    resize_on_border = true
    hover_icon_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

