# Programs

$menu = hyprlauncher
$statusBar = waybar
$notificationCenter = swaync
$fileManager = dolphin
$wallpaperManager = hyprpaper

$terminal = wezterm

$passwordManager = 1password
$webBrowser = zen-browser

# Auto-start

exec-once = $statusBar
exec-once = $notificationCenter
exec-once = $passwordManager --silent
exec-once = $wallpaperManager
