# Programs

$menu = hyprlauncher
$statusBar = waybar
$notificationCenter = swaync
$fileManager = dolphin

$terminal = wezterm

$passwordManager = 1password
$webBrowser = zen-browser

# Auto-start

exec-once = $statusBar
exec-once = $notificationCenter
